# Generated by Django 4.2 on 2023-04-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wooapp', '0002_order_orderupdate_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailsubcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
