# Generated by Django 4.2 on 2023-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wooapp', '0003_emailsubcription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pname', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pnumber', models.IntegerField()),
            ],
        ),
    ]
