# Generated by Django 4.2 on 2023-04-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wooapp', '0004_returnproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
